In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [3]:
plt.rcParams['figure.figsize'] = (10,10)
plt.rcParams.update({'font.size': 22})

Matrix

In [4]:
x = np.array([[1,0,0],[0,1,0]])

print(x)

[[1 0 0]
 [0 1 0]]


In [9]:
row = x.shape[0]
col = x.shape[1]

print("rows = ", row , "\ncols = ", col)

rows =  2 
cols =  3


Basic Operations

Matrix Addition

In [15]:
matrix_1 = np.array([[1,5, 3],[4,5,0],[4,8,9]])
matrix_2 = np.array([[3,1,3],[6,1,2],[9,8,9]])

print("Matrix 1: \n", matrix_1, "\n\n", "Matrix 2: \n", matrix_2)

Matrix 1: 
 [[1 5 3]
 [4 5 0]
 [4 8 9]] 

 Matrix 2: 
 [[3 1 3]
 [6 1 2]
 [9 8 9]]


In [19]:
add_ = matrix_1 + matrix_2
print("Addition: \n", add_)

Addition: 
 [[ 4  6  6]
 [10  6  2]
 [13 16 18]]


In [21]:
matrix_3 = np.array([[1,5, 3],[4,5,0]])
matrix_4 = np.array([[3,1,3],[6,1,2],[9,8,9]])

try:
    add_2 = matrix_3 + matrix_4
    print("Addition: \n", add_2)
except:
    print("Cannot add matrices of different dimensions")

Cannot add matrices of different dimensions


Commutative Property 

x+y=y+x